Refactored nepali number
opensource-nepal/py-nepali pull request #30
Opened 2023-02-20 15:24 UTC by aj3sh

- Changed the method names, made more readable.
- Refactored functionalities of `number`. 
- Depreciated old methods.
- Added black's check only on pre-commit hook.

2023-02-20 16:40 UTC, sugat009 requested changes

2023-02-20 16:40 UTC, sugat009 commented on nepali/number.py
> +            converted_number.append(str(NP_NUMBERS[int(n)]))
NP_NUMBERS[int(n)] should return a str value and this conversion might not be necessary?

2023-02-20 16:40 UTC, sugat009 commented on nepali/number.py
> +    nepali_number_set = set(NP_NUMBERS)
not really necessary?

2023-02-20 16:40 UTC, sugat009 commented on nepali/number.py
> +def add_comma(number: Any, convert=False) -> str:
convert unused

2023-02-20 17:25 UTC, aj3sh commented on nepali/number.py
> +    nepali_number_set = set(NP_NUMBERS)
used for avoiding the O(n^2) loop below.

2023-02-21 03:11 UTC, sugat009 requested changes

2023-02-21 03:11 UTC, sugat009 commented on nepali/number.py
> +    nepali_number_set = set(NP_NUMBERS)
`if n in nepali_number_set:`
i think this can be done with `NP_NUMBERS` itself

2023-02-21 03:38 UTC, aj3sh commented on nepali/number.py
> +    nepali_number_set = set(NP_NUMBERS)
`n in nepali_number_set` is used inside a loop and using a set gives O(1) time complexity. If we use `list` here it becomes O(N).

2023-02-21 13:28 UTC, aj3sh commented on nepali/number.py
> +            converted_number.append(str(NP_NUMBERS[int(n)]))
Updated

2023-02-21 13:28 UTC, aj3sh commented on nepali/number.py
> +def add_comma(number: Any, convert=False) -> str:
Updated

2023-02-21 13:35 UTC, sugat009 approved these changes

2023-02-21 13:35 UTC, merged