Refactoring, Coding Standard, and Fomatting done
opensource-nepal/py-nepali pull request #32
Opened 2023-02-25 08:34 UTC by aj3sh

- Added CONTRIBUTION.md
- Bug fix for django templatetags
- None checking update with PEP8 standard
- nepali.utils updated
- Code formatted
- Removed black check only params on pre-commit hooks

2023-02-25 09:50 UTC, sugat009 requested changes

2023-02-25 09:50 UTC, sugat009 commented on nepali/datetime/utils.py
> +    if type(datetime_object) == nepalidatetime:
lets go with `isinstance(datetime_object, nepalidatetime)` as it's more pythonic

2023-02-25 09:50 UTC, sugat009 commented on requirements.txt
> +pre-commit==2.21.0
any particular reasons for the downgrade?

2023-02-25 09:52 UTC, sugat009 requested changes

2023-02-25 09:52 UTC, sugat009 commented on CONTRIBUTION.md
> +# How to contribute
Lets mention this file in readme.md as well

2023-02-25 11:35 UTC, aj3sh commented on requirements.txt
> +pre-commit==2.21.0
That was a mistake during the upgrading process.

2023-02-25 11:35 UTC, aj3sh commented on CONTRIBUTION.md
> +# How to contribute
Done

2023-02-26 05:44 UTC, aj3sh commented on nepali/datetime/utils.py
> +    if type(datetime_object) == nepalidatetime:
Done

2023-02-26 05:44 UTC, aj3sh commented on nepali/datetime/utils.py
> +    if type(datetime_object) == nepalidatetime:
Test cases added to verify this

2023-02-26 09:57 UTC, sugat009 approved these changes

2023-02-26 09:57 UTC, merged