Added parse functionality for nepalinumber class
opensource-nepal/py-nepali pull request #34
Opened 2023-02-26 10:42 UTC by aj3sh

2023-03-05 11:07 UTC, sugat009 requested changes

2023-03-05 11:07 UTC, sugat009 commented on nepali/number/nepalinumber.py
> +NP_NUMBERS_SET = set(NP_NUMBERS)
Let's create a separate NP_NUMBERS_SET variable for reuse since, it's been used a lot

2023-03-05 11:07 UTC, sugat009 commented on nepali/number/nepalinumber.py
> +    def _raiseParseException(self, obj, ex_class: Type[Exception] = ValueError):
Let's go with snake case if this is not required?

2023-03-05 11:07 UTC, sugat009 commented on nepali/number/nepalinumber.py
> +                    # decimal was already founded
found itself is past :D

2023-03-05 11:07 UTC, sugat009 commented on nepali/number/nepalinumber.py
> +        while i < len(value):
i don't really see a need to loop using `while` when `for i in value` can be done

2023-03-05 11:07 UTC, sugat009 commented on nepali/tests/test_number.py
> +        self.assertEqual(type(num.value), int)
`assertIsInstance` would be more appropriate here

2023-03-05 11:07 UTC, sugat009 commented on nepali/tests/test_number.py
> +        class _test:
let's initialize variables in setup classmethod
REF: https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass

2023-03-05 11:07 UTC, sugat009 commented on nepali/number/nepalinumber.py
> +        while i < len(value):
nevermind, found it is linked with variable i from line 71

2023-03-05 11:11 UTC, aj3sh commented on nepali/number/nepalinumber.py
> +NP_NUMBERS_SET = set(NP_NUMBERS)
I didn't get you. NP_NUMBERS_SET is a separate variable.

2023-03-05 11:14 UTC, aj3sh commented on nepali/tests/test_number.py
> +        self.assertEqual(type(num.value), int)
I am strictly checking the type here. `isinstance` returns true for subclasses, which is not okay for my test case.

2023-03-05 11:16 UTC, aj3sh commented on nepali/tests/test_number.py
> +        class _test:
These variables are entirely different for different test cases. So the setup method will not help here.

2023-03-05 11:17 UTC, aj3sh commented on nepali/tests/test_number.py
> +        self.assertEqual(type(num.value), int)
Reference example is in Line 219: `test_nepalinumber_parses_inherited_int`

2023-03-06 05:19 UTC, aj3sh commented on nepali/number/nepalinumber.py
> +                    # decimal was already founded
Fixed

2023-03-06 05:19 UTC, aj3sh commented on nepali/number/nepalinumber.py
> +    def _raiseParseException(self, obj, ex_class: Type[Exception] = ValueError):
Done

2023-03-06 05:19 UTC, aj3sh commented on nepali/number/nepalinumber.py
> +NP_NUMBERS_SET = set(NP_NUMBERS)
Done

2023-03-09 14:22 UTC, sugat009 approved these changes

2023-03-09 15:04 UTC, merged