Feature/arithmetic operations in nepalinumbers
opensource-nepal/py-nepali pull request #39
Opened 2023-03-15 15:52 UTC by sugat009

2023-03-18 04:17 UTC, aj3sh commented on nepali/number/nepalinumber.py
> +    def __convert_or_return(self, obj) -> Union["nepalinumber", object]:
`Union["nepalinumber", object]`: nepalinumber is also a subclass of object. Isn't it same as `Any`?

2023-03-18 04:21 UTC, aj3sh commented on nepali/number/nepalinumber.py
> +    def __add(self, other) -> Union[int, float]:
Just asking if this method is helping as we are not using methods like this on subtraction and division.

2023-03-18 05:19 UTC, aj3sh requested changes

2023-03-18 05:19 UTC, aj3sh commented on nepali/tests/test_number.py
> +        cls.nepalinumber_negative_float_0_5 = number.nepalinumber(-0.5)
I can see that you are using saving frequently used `nepalinumber` for memory management, but it made the test case illegible and this becomes unmaintainable in the future. I suggest using a different caching mechanism.

Here is an example (nepalinumber proxy):
```python
from nepali.number import nepalinumber as _nepalinumber


_nm_cache = {}


def nepalinumber(val):
    if val not in _nm_cache:
        _nm_cache[val] = _nepalinumber(val)
    return _nm_cache[val]
    

nepalinumber(1)  # nepalinumber is called
nepalinumber(1)  # cached
```

2023-03-18 05:24 UTC, aj3sh commented
@sugat009 Please add "relates" with the Issue link on the PR description.

2023-03-19 03:40 UTC, sugat009 commented on nepali/number/nepalinumber.py
> +    def __convert_or_return(self, obj) -> Union["nepalinumber", object]:
everything is a subclass of object and can be written as any but im trying to be explicit here to indicate that either `nepalinumber` of `object` will be returned

2023-03-19 03:41 UTC, sugat009 commented on nepali/number/nepalinumber.py
> +    def __add(self, other) -> Union[int, float]:
in case of multiplication and addition, `a + b = b + a` and `a * b = b * a` but not in case of other operations and im pretty sure that the code itself is self explanatory

2023-03-19 03:44 UTC, sugat009 commented on nepali/tests/test_number.py
> +        self.assertNotIsInstance(self.random_object, int)
this is to ensure that if by any chance that random_object is changed then, these test cases will fail to indicate that the types of params or args being tested is not of expected type

2023-03-19 03:50 UTC, sugat009 commented on nepali/tests/test_number.py
> +        cls.nepalinumber_negative_float_0_5 = number.nepalinumber(-0.5)
in unit testing, the objective is to write dumb code that just works, if the function like mentioned in this comment is used then, we'll have to write unit tests for it too
in python unit testing, these objects are called fixtures and it's usually a standard practice to create the objects that you are going to use in the tests in the setup of the test class and although it may seem unmaintainable it is beneficial when like changing the objects value which gets reflected for the entire test case class

2023-03-19 04:28 UTC, aj3sh commented on nepali/tests/test_number.py
> +        cls.nepalinumber_negative_float_0_5 = number.nepalinumber(-0.5)
So what is the benefits of write the code 
```python
self.assertEqual(self.nepalinumber_integer_10 + 1, self.nepalinumber_integer_11)
``` 
over 
```python
self.assertEqual(nepalinumber(10)+ 1, nepalinumber(11))
```

Ignore my above proxy method.

2023-03-19 08:39 UTC, sugat009 commented on nepali/tests/test_number.py
> +        cls.nepalinumber_negative_float_0_5 = number.nepalinumber(-0.5)
```self.assertEqual(self.nepalinumber_integer_10 + 1, self.nepalinumber_integer_11)```
writing this would mean that the objects are initialized only once during setup and not for each test and if there is an error in initialization its captured in the setup not during test

2023-03-19 12:43 UTC, aj3sh commented on nepali/tests/test_number.py
> +        self.assertNotIsInstance(self.random_object, int)
Why are we not using `object` here? If you are so afraid that random_object gets changed why don't you use the `setUp` method (but I'd avoid this)?  I don't see this test case as necessary as it is not part of our development.

2023-03-19 13:06 UTC, aj3sh commented on nepali/tests/test_number.py
> +        cls.nepalinumber_negative_float_0_5 = number.nepalinumber(-0.5)
I am not getting a clear picture. We will discuss it later.

But in my POV if test cases fail due to our programming error then let it be. And it should be clear why and where it is failing.

And how are we making sure that the variable like `nepalinumber_integer_10` aren't changed by other test cases or any **in-place operations in the future**? Taking these variables as fixtures might be a bad idea.

2023-03-31 11:49 UTC, merged