Added class nepaliweek with additional minor fixes
opensource-nepal/py-nepali pull request #40
Opened 2023-03-29 15:08 UTC by aj3sh

- Nepali months constant data moved to `datetime.constants`
- Introduced nepaliweek
- Optimization and refactoring for `nepalimonth`
- Integrated `nepaliweek` with `nepalidatetime`
- Depreciated `NepaliChar` and `EnglishChar` methods

2023-04-01 14:41 UTC, sugat009 requested changes

2023-04-01 14:41 UTC, sugat009 commented on nepali/datetime/_nepaliweek.py
> +    Sunday: 1,
Let's make sunday as 0 and saturday as 6 to be aligned with python's weekday feature of monday as 0 and sunday as 6

2023-04-03 11:38 UTC, theoctober19th approved these changes

2023-04-03 14:49 UTC, aj3sh commented on nepali/datetime/_nepaliweek.py
> +    Sunday: 1,
Updated

2023-04-05 02:08 UTC, sugat009 approved these changes

2023-04-05 02:08 UTC, merged