Added str_ne method on nepalinumber
opensource-nepal/py-nepali pull request #41
Opened 2023-04-05 12:35 UTC by aj3sh

Added `str_ne` method on `nepalinumber` for Devanagari string output.

2023-04-07 09:29 UTC, sugat009 requested changes

2023-04-07 09:29 UTC, sugat009 commented on nepali/number/nepalinumber.py
> +        :return: Nepali number
how about `:return: Stringified Nepali number`

2023-04-10 14:45 UTC, aj3sh commented on nepali/number/nepalinumber.py
> +        :return: Nepali number
Sounds good

2023-04-10 16:10 UTC, aj3sh commented on nepali/number/nepalinumber.py
> +        :return: Nepali number
Updated

2023-04-10 16:13 UTC, sugat009 approved these changes

2023-04-10 16:13 UTC, merged