Reduce complexity of `transform` function.
opensource-nepal/py-nepali pull request #50
Opened 2023-05-09 15:07 UTC by theoctober19th

This fixes #45.

2023-05-09 15:55 UTC, aj3sh requested changes

2023-05-09 15:55 UTC, aj3sh commented on nepali/datetime/parser/validators.py
> +        am_pm = data.get("p", "am").lower() or "am"
I suggest using `data.get("p", "").lower() or "am"` as implemented before so that we can maintain the default value ('am') from a single point.

Also, do we need to apply `lower()` as we have already used it on `__convert_12_hour_to_24_hour`?

2023-05-09 15:55 UTC, aj3sh commented on nepali/datetime/parser/validators.py
> +def __calculate_month(data: dict) -> int:
This method will also return `nepalimonth` object, so the return type will be `Union[nepalimonth, int]`.

Alternatively, we can modify the code to only return nepalimonth using the following code.
```python
if "m" in data:
    month_data = data["m"]
elif "b" in data:
    month_data = data["b"]
elif "B" in data:
    month_data = data["B"]
else:
    month_data = 1

return nepalimonth(month_data)
```

2023-05-09 15:56 UTC, sugat009 requested changes

2023-05-09 15:56 UTC, sugat009 commented on nepali/datetime/parser/validators.py
> +    Args:
In this project, we have been using doc string formatting style of reST. For consistency, I request you to change the docstrings in this PR to reST format as well.
Ref: https://gist.github.com/nipunsadvilkar/fec9d2a40f9c83ea7fd97be59261c400#--rest 
https://peps.python.org/pep-0287/#copyright

2023-05-09 16:51 UTC, aj3sh approved these changes
Looks good to me.

2023-05-10 14:18 UTC, sugat009 approved these changes

2023-05-10 14:18 UTC, sugat009 commented on nepali/datetime/parser/validators.py
> +        am_pm = data.get("p", "am").lower() or "am"
I think `am_pm = data.get("p", "am").lower()` would be sufficient.

2023-05-10 14:18 UTC, sugat009 commented on nepali/datetime/parser/validators.py
> +def __calculate_weekday(data: dict) -> Optional[int]:
Add return type `nepaliweek` as well.

2023-05-10 14:18 UTC, merged