test: nepali numbers module
opensource-nepal/py-nepali pull request #74
Opened 2023-11-28 07:32 UTC by golesuman

## Description

Add tests with full test coverage

## Type of Change

Please mark the appropriate option below to describe the type of change your pull request introduces:

- [ ] Bug fix
- [ ] New feature
- [x] Enhancement
- [ ] Documentation update
- [ ] Refactor
- [ ] Other (please specify)

## Checklist

- [x] I have used [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
      Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
- [x] I have used pre-commit hooks.
- [ ] I have added/updated the necessary documentation on `README.md`.
- [ ] I have updated `CHANGELOG.md` for the significant changes.
- [x] I have added appropriate test cases (if applicable) to ensure the changes are functioning correctly.
- [ ] My pull request has a clear title and description.

## Additional Notes

[Add any additional notes or context that you think the reviewers should know about.]

By submitting this pull request, I confirm that I have read and complied with the contribution guidelines of this project.

2023-11-28 15:28 UTC, sugat009 commented
Hello @golesuman , thank you for your contribution. 
The tests that you have added might have been misplaced. `TestNumber` class is for the tests of the `number` package as a whole. We try to make sure that the test classes only test one particular entity, so `TestNepaliNumberMethods` class in the same test file might be a better choice to add your tests.
Also, we follow the convention of writing commit messages of the form `<type>: <verb> <what was done>`.
For example in your case it might be `test: Add object representation and equality tests for nepalinumber`.

2023-11-28 15:30 UTC, sugat009 requested changes

2023-11-28 15:30 UTC, sugat009 commented on nepali/tests/test_number.py
> +    def test_object_representation(self):
issue: Tests in wrong class, move to correct class

2023-11-29 04:47 UTC, sugat009 commented
@golesuman Can you also squash your commit into one commit?

2023-11-29 05:19 UTC, sugat009 requested changes

2023-11-29 05:19 UTC, sugat009 commented on nepali/tests/test_number.py
> +    def test_object_representation(self):
issue: The changes have been copied here but the previous changes have not been removed

2024-01-13 06:21 UTC, aj3sh commented
Closing this stale PR.
cc: @sugat009

2024-01-13 06:21 UTC, closed without merging